=== wrvthlss/design-token-prod/schemas/token-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Schema",
  "type": "object",
  "properties": {
    "fontSize": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["fontSize"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "shadows": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["shadow"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "fontFamily": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9-]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["fontFamilies"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "fontWeight": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9-]+$": {
          "type": "object",
          "patternProperties": {
            "^[0-9]+$": {
              "type": "object",
              "properties": {
                "value": { "type": "string" },
                "type": { "type": "string", "enum": ["fontWeights"] }
              },
              "required": ["value", "type"]
            }
          },
          "additionalProperties": false
        }
      }
    },
    "lineHeight": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["dimension"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "letterSpacing": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["letterSpacing"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "colors": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z0-9]+$": {
              "type": "object",
              "properties": {
                "value": { "type": "string" },
                "type": { "type": "string", "enum": ["color"] }
              },
              "anyOf": [
                { "required": ["value", "type"] },
                {
                  "patternProperties": {
                    "^(dark|light)$": {
                      "type": "object",
                      "properties": {
                        "value": { "type": "string" },
                        "type": { "type": "string", "enum": ["color"] }
                      },
                      "required": ["value", "type"]
                    }
                  }
                }
              ]
            }
          }
        }
      }
    },
    "background": {
      "type": "object",
      "properties": {
        "blur": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["dimension"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "buttonDisabled": {
      "type": "object",
      "properties": {
        "value": { "type": "string" },
        "type": { "type": "string", "enum": ["opacity"] }
      },
      "required": ["value", "type"]
    },
    "size": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["dimension"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "spacing": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["dimension"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "borderRadius": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9-]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["dimension"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "borderWidth": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "properties": {
            "value": { "type": "string" },
            "type": { "type": "string", "enum": ["dimension"] }
          },
          "required": ["value", "type"]
        }
      }
    },
    "input": { "type": "object"},
    "checkbox": { "type": "object" },
    "radio": { "type": "object" },
    "textarea": { "type": "object" },
    "card": { "type": "object" },
    "button": { "type": "object" },
    "divider": { "type": "object" },
    "cta": { "type": "object" },
    "modal": { "type": "object" },
    "overlay": { "type": "object" }
  },
  "additionalProperties": false
}

=== wrvthlss/design-token-prod/tokens/semantic.json
{
  "input": {
    "border": {
      "default": {
        "value": {
          "color": "{global.colors.gradient.500}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      },
      "resting": {
        "value": {
          "color": "{global.colors.accents.100.dark}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      }
    },
    "icon": {
      "fill": {
        "default": {
          "value": "{global.colors.alert.info.dark}",
          "type": "color"
        },
        "resting": {
          "value": "{global.colors.secondary.200.dark}",
          "type": "color"
        }
      }
    },
    "background": {
      "default": {
        "value": "{global.colors.primary.100}",
        "type": "color"
      }
    },
    "cursor": {
      "fill": {
        "default": {
          "value": "{global.colors.alert.info.dark}",
          "type": "color"
        }
      }
    },
    "text": {
      "fontWeight": {
        "value": "{global.fontWeight.regular}",
        "type": "fontWeights"
      },
      "fontSize": {
        "value": "{global.fontSize.sm}",
        "type": "fontSizes"
      },
      "lineHeight": {
        "value": "{global.lineHeight.4}",
        "type": "lineHeights"
      }
    },
    "borderRadius": {
      "value": "{global.borderRadius.rounded-md}",
      "type": "borderRadius"
    }
  },
  "checkbox": {
    "border": {
      "deselected": {
        "value": {
          "color": "{global.colors.accents.100.dark}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      },
      "selected": {
        "value": {
          "color": "{global.colors.accents.300.dark}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      }
    },
    "label": {
      "fill": {
        "value": "{global.colors.secondary.100.dark}",
        "type": "color"
      }
    },
    "fill": {
      "selected": {
        "value": "{global.colors.accents.300.dark}",
        "type": "color"
      }
    },
    "text": {
      "fontWeight": {
        "value": "{global.fontWeight.regular}",
        "type": "fontWeights"
      },
      "fontSize": {
        "value": "{global.fontSize.md}",
        "type": "fontSizes"
      },
      "lineHeight": {
        "value": "{global.lineHeight.3}",
        "type": "lineHeights"
      }
    },
    "borderRadius": {
      "value": "{global.borderRadius.rounded-md}",
      "type": "borderRadius"
    }
  },
  "radio": {
    "border": {
      "deselected": {
        "value": {
          "color": "{global.colors.accents.100.dark}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      }
    },
    "fill": {
      "selected": {
        "value": "{global.colors.accents.300.dark}",
        "type": "color"
      }
    },
    "text": {
      "fontWeight": {
        "value": "{global.fontWeight.regular}",
        "type": "fontWeights"
      },
      "fontSize": {
        "value": "{global.fontSize.md}",
        "type": "fontSizes"
      },
      "lineHeight": {
        "value": "{global.lineHeight.3}",
        "type": "lineHeights"
      }
    },
    "borderRadius": {
      "value": "{global.borderRadius.rounded-full}",
      "type": "borderRadius"
    }
  },
  "textarea": {
    "border": {
      "default": {
        "value": {
          "color": "{global.colors.gradient.500}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      }
    },
    "icon": {
      "fill": {
        "default": {
          "value": "{global.colors.alert.info.dark}",
          "type": "color"
        }
      }
    },
    "text": {
      "fontWeight": {
        "value": "{global.fontWeight.regular}",
        "type": "fontWeights"
      },
      "fontSize": {
        "value": "{global.fontSize.sm}",
        "type": "fontSizes"
      },
      "lineHeight": {
        "value": "{global.lineHeight.4}",
        "type": "lineHeights"
      }
    },
    "borderRadius": {
      "value": "{global.borderRadius.rounded-md}",
      "type": "borderRadius"
    }
  },
  "card": {
    "border": {
      "large": {
        "outline": {
          "value": {
            "color": "{global.colors.gradient.500}",
            "width": "1",
            "style": "solid"
          },
          "type": "border"
        }
      }
    },
    "background": {
      "default": {
        "value": "{global.colors.secondary.400.dark}",
        "type": "color"
      }
    },
    "fill": {
      "large": {
        "outline": {
          "value": "{global.colors.secondary.500.dark}",
          "type": "color"
        }
      }
    },
    "borderRadius": {
      "value": "{global.borderRadius.rounded-lg}",
      "type": "borderRadius"
    }
  },
  "button": {
    "border": {
      "default": {
        "value": {
          "color": "{global.colors.secondary.100.dark}",
          "width": "1",
          "style": "solid"
        },
        "type": "border"
      }
    },
    "text": {
      "fill": {
        "default": {
          "value": "{global.colors.secondary.100.dark}",
          "type": "color"
        }
      },
      "fontWeight-small": {
        "value": "{global.fontWeight.semibold}",
        "type": "fontWeights"
      },
      "fontWeight-large": {
        "value": "{global.fontWeight.bold}",
        "type": "fontWeights"
      },
      "fontSize-small": {
        "value": "{global.fontSize.sm}",
        "type": "fontSizes"
      },
      "fontSize-large": {
        "value": "{global.fontSize.md}",
        "type": "fontSizes"
      },
      "lineHeight-small": {
        "value": "{global.lineHeight.3}",
        "type": "lineHeights"
      },
      "lineHeight-large": {
        "value": "{global.lineHeight.4}",
        "type": "lineHeights"
      }
    },
    "icon": {
      "fill": {
        "default": {
          "value": "{global.colors.alert.info.dark}",
          "type": "color"
        }
      }
    },
    "borderRadius-small": {
      "value": "{global.borderRadius.rounded-lg}",
      "type": "borderRadius"
    },
    "borderRadius-large": {
      "value": "{global.borderRadius.rounded-2xl}",
      "type": "borderRadius"
    }
  },
  "divider": {
    "fill": {
      "default": {
        "value": "{global.colors.accents.100.dark}",
        "type": "color"
      }
    },
    "width": {
      "default": {
        "value": "1",
        "type": "borderWidth"
      }
    }
  },
  "cta": {
    "icon": {
      "fill": {
        "alt": {
          "value": "{global.colors.secondary.100.dark}",
          "type": "color"
        },
        "default": {
          "value": "{global.colors.alert.info.dark}",
          "type": "color"
        }
      }
    },
    "label": {
      "fill": {
        "value": "{global.colors.secondary.100.dark}",
        "type": "color"
      }
    },
    "text": {
      "fontWeight": {
        "value": "{global.fontWeight.semibold}",
        "type": "fontWeights"
      },
      "fontSize": {
        "value": "{global.fontSize.md}",
        "type": "fontSizes"
      }
    }
  },
  "modal": {
    "icon": {
      "fill": {
        "value": "{global.colors.secondary.100.dark}",
        "type": "color"
      }
    },
    "background": {
      "default": {
        "value": "{global.colors.primary.100}",
        "type": "color"
      }
    },
    "dropshadow": {
      "default": {
        "value": "{global.shadows.shadow.6}",
        "type": "boxShadow"
      }
    },
    "borderRadius-topLeft": {
      "value": "{global.borderRadius.rounded-2xl}",
      "type": "borderRadius"
    },
    "borderRadius-bottomRight": {
      "value": "{global.borderRadius.none}",
      "type": "borderRadius"
    },
    "borderRadius-bottomLeft": {
      "value": "{global.borderRadius.none}",
      "type": "borderRadius"
    },
    "borderRadius-topRight": {
      "value": "{global.borderRadius.rounded-2xl}",
      "type": "borderRadius"
    }
  }
}
